### ISSUE TITLE
Deno Thunderbolt

### ISSUE THREAD

**Issue by hashrock** [denolib/animated-deno-logo#3]
![deno-circle-thunder_7](https://user-images.githubusercontent.com/3132889/61991522-3dc8f180-b08c-11e9-9c58-c4fac378fdb4.gif)

I am considering updating the logo to solve issue #2 .

@ry 
Is there too much lightning?😆

**Comment by ry** [comment]
Oh I love it! But it would be fun if it was less frequent - to reward viewers who stare at it for a while.

**Comment by hashrock** [comment]
@ry 
Sure! How about this?

![deno-circle-thunder_10](https://user-images.githubusercontent.com/3132889/61992013-7cae7580-b093-11e9-96eb-2213db47e2fb.gif)

**Comment by ry** [comment]
Beautiful !

**Comment by hashrock** [comment]
Thanks! I'll make pull request for docs 👍

**Comment by hashrock** [comment]
PR marged.

Close #2
