### ISSUE TITLE
Optimize image size

### ISSUE THREAD

**Issue by ry** [denolib/animated-deno-logo#4]
Currently the image https://denolib.github.io/animated-deno-logo/deno-circle-thunder.gif is about 2mb... It's very large and recently when visiting an uncached version of the manual, I noticed how slow it was to load.

**Comment by hashrock** [comment]
Now 2.04mb -> 0.34mb!

- I used this site http://gifgifs.com/optimizer/
- Resize 300px * 300px to 200px * 200px
- Apply `Remove every 2nd frame` with frame delay 80ms
- Lossy GIF level 80

The original quality file is saved as `deno-circle-thunder_orig.gif`.
